import type { NextPage } from "next";
import Head from "next/head";
import CreateChannelButton from "../components/atoms/CreateChannelButton";
import Channels from "../components/organisms/Channels";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center gap-8 min-h-screen p-4 bg-slate-800">
        <h1 className="text-3xl text-white font-bold">Channels</h1>
        <Channels />
        <CreateChannelButton />
      </main>
    </>
  );
};

export default Home;
